version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: skillgap
      POSTGRES_USER: skilladmin
      POSTGRES_PASSWORD: skillpass
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: skillgap
      KC_DB_USERNAME: skilladmin
      KC_DB_PASSWORD: skillpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    ports:
      - "8081:8080"
    depends_on:
      - postgres
